name: build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        strategy:
          matrix:
            os:
              - ubuntu-latest
              - windows-latest
              - macos-latest
        runs-on: ${{matrix.os}}
        steps:
            - uses: actions/checkout@v1
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '9.0.x'
            - name: Set env
              run: |
                echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" >> $GITHUB_ENV
                echo "DOTNET_hostBuilder:reloadConfigOnChange=false" >> $GITHUB_ENV
            - name: Clean
              run: |
                dotnet clean ./NRPC.sln --configuration Release
                dotnet nuget locals all --clear
            - name: Build
              run: dotnet build -c Release
            - name: Test
              run: |
                cd test/NRPC.Test
                dotnet test --logger "console;verbosity=detailed"